# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include: 
    - develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '0'
  Patch: '1'
  workingDir: "src/BxBlazor"

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: 'src/**/*.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'src/Nuget.config'
    includeNuGetOrg: true
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    packagesToPack: 'src/BxBlazor/**/*.csproj'
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)' 

- task: DotNetCoreCLI@2
  displayName: 'Nuget push to BxBlazor feed'
  inputs:
    workingDirectory: '$(workingDir)'
    command: push
    publishVstsFeed: '000f425a-ccb5-4b06-8458-0a352978d151/84a32888-ceea-438a-b74b-ea0998a1d69b'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: 'src/BackendApi/*.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/BackendApi"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    ArtifactName: 'drop'

- task: AzureFunctionApp@1
  displayName: 'publish to azure functions app'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(c88875e6-420c-4b77-81f5-f3a23368e07a)'
    appType: 'functionApp'
    appName: 'backend-challenge'
    deploymentMethod: 'auto'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SampleProject/Client/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/dist'
    zipAfterPublish: false
    modifyOutputPath: true
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(c88875e6-420c-4b77-81f5-f3a23368e07a)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name bxblazor --destination ‘$web’ --source ./'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/dist/Client/blazorwasm.Client/dist'